version: '3.8'

services:

  server:
    build:
      context: ../../
      dockerfile: docker/dev/server/Dockerfile
      args:
        WORKDIR: ${PROJECT_ROOT}
    networks:
      - local
    container_name: server
    env_file:
      - ../../.env
    depends_on:
      - db
    expose:
      - "8080"
    environment:
      - DOCKER_MYSQL_HOST_MACHINE=false
      - DOCKER=true
    ports:
      - "8080:8080"

  pma:
    container_name: pma
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:8081"
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db
    networks:
      - local

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: db
    expose:
      - "3306"
    networks:
      - local
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

networks:
  local:
