version: '3.8'

services:

  server:
    build:
      context: ${APP_ROOT}
      args:
        WORKDIR: ${PROJECT_ROOT}
    networks:
      - local
    volumes:
      - ${PROJECT_ROOT}:${PROJECT_ROOT}
    container_name: server
    depends_on:
      - db
    expose:
      - "8080"
    ports:
      - "8080:8080"

  pma:
    container_name: pma
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:8081"
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db
    networks:
      - local

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: db-migrate
    expose:
      - "3306"
    networks:
      - local
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

networks:
  local:
