version: '3.8'

services:

  server:
    build:
      dockerfile: docker/server/Dockerfile.development
    env_file:
      - ".env.development"

  db:
    env_file:
      - ".env.development"
    volumes:
      - ${APP_ROOT}/docker/db/dbdata:/var/lib/mysql
      - ${APP_ROOT}/docker/db/docker-entrypoint-initdb.d/test-db.sql:/docker-entrypoint-initdb.d/test-db.sql

networks:
  local:
